# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exclusao_mutua.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xclusao_mutua.proto\x12\x0e\x65xclusao_mutua\"\'\n\rPedidoRequest\x12\x16\n\x0eid_do_processo\x18\x01 \x01(\x05\"\x10\n\x0ePedidoResponse2\xb5\x01\n\x0eServicoEleicao\x12P\n\rIniciarPedido\x12\x1d.exclusao_mutua.PedidoRequest\x1a\x1e.exclusao_mutua.PedidoResponse\"\x00\x12Q\n\x0e\x45ncerrarPedido\x12\x1d.exclusao_mutua.PedidoRequest\x1a\x1e.exclusao_mutua.PedidoResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exclusao_mutua_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEDIDOREQUEST._serialized_start=40
  _PEDIDOREQUEST._serialized_end=79
  _PEDIDORESPONSE._serialized_start=81
  _PEDIDORESPONSE._serialized_end=97
  _SERVICOELEICAO._serialized_start=100
  _SERVICOELEICAO._serialized_end=281
# @@protoc_insertion_point(module_scope)
